name: Appium Android

on:
  push:
    branches: [ javaclient8_2 ]
  pull_request:
    branches: [ javaclient8_2 ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        config:
          - { api-level: 27, target: default, arch: x86, port: 4723 }
          - { api-level: 28, target: default, arch: x86, port: 4724 }
          - { api-level: 29, target: default, arch: x86, port: 4725 }
          #- { api-level: 34, target: google_apis, arch: x86_64, port: 4726 }
          #- { api-level: 33, target: google_apis, arch: x86_64, port: 4727 }
          #- { api-level: 32, target: google_apis, arch: x86_64, port: 4728 }
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup appium
        run: |
          npm install -g appium@v2.0.1
          appium driver install uiautomator2
          npm install -g appium-doctor
          appium -v
          appium -p ${{ matrix.config.port }} &>/dev/null &

      - name: Run appium android tests
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.config.api-level }}
          target: ${{ matrix.config.target }}
          arch: ${{ matrix.config.arch }}
          script: |
            echo "Appium port: ${{ matrix.config.port }}"
            mvn clean test -Pandroid -Dapi.level=${{ matrix.config.api-level }} -DappiumPort=${{ matrix.config.port }}