name: Appium Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 28 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup appium
        run: |
          npm install -g appium@v2.0.1
          npm install -g appium-uiautomator2-driver
          appium-doctor
          appium driver list
          appium -v
          appium &>/dev/null &

      - name: Run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }} #29
          script: mvn clean test -Pandroid
  
