name: Appium iOS

on:
  push:
    branches: [ ios ]
  pull_request:
    branches: [ ios ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - run: |
          npm install -g appium@v2.0.1
          appium -v
          appium &>/dev/null &
          mvn clean test -PiOS