name: Appium Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'


      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '35.0.1'

      - name: Install Node.js and Appium
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install -g appium
      - run: npm install -g appium-doctor
      - run: npm install -g appium-uiautomator2-driver

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          architecture: x86_64
          profile: Nexus-5
          script: emulator -no-window -no-audio
          licenses: android-sdk-preview-license-52d11cd2

      - name: Build and Test with Maven
        run: mvn clean test