name: Appium Android

on:
  push:
    branches: [ javaclient8_2 ]
  pull_request:
    branches: [ javaclient8_2 ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 24, 28, 29]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup appium
        run: |
          npm install -g appium@v2.0.1
          appium driver install uiautomator2
          npm install -g appium-doctor
          appium -v
          chmod +x find_free_port.sh
          port=$(bash -c './find_free_port.sh')
          appium --port $port &>/dev/null &

      - name: Run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }} #29
          script: mvn clean test -Pandroid -Dappium.port=$port -Dapi.level=${{ matrix.api-level }}
