name: Appium Android

on:
  push:
    branches: [ javaclient8_2 ]
  pull_request:
    branches: [ javaclient8_2 ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        config:
          - { api-level: 24, port: 4723 }
          - { api-level: 28, port: 4724 }
          - { api-level: 29, port: 4725 }
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup appium
        run: |
          npm install -g appium@v2.0.1
          appium driver install uiautomator2
          npm install -g appium-doctor
          appium -v
          appium -p ${{ matrix.config.port }} &>/dev/null &

      - name: Run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.config.api-level }}
          script: |
            echo "Appium port: ${{ matrix.config.port }}"
            mvn clean test -Pandroid -Dapi.level=${{ matrix.config.api-level }} -DappiumPort=${{ matrix.config.port }}