name: Appium iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        config:
          - { device-name: iPhone 14 Pro Max, appium-port: 4723, wda-port: 8101 }
          - { device-name: iPhone 14 Pro, appium-port: 4724, wda-port: 8102 }
          - { device-name: iPhone 14 Plus , appium-port: 4725, wda-port: 8103 }
          - { device-name: iPhone 14 , appium-port: 4726, wda-port: 8104 }
          - { device-name: iPhone 13 Pro Max, appium-port: 4727, wda-port: 8105 }
          - { device-name: iPhone 13 Pro, appium-port: 4728, wda-port: 8106 }
          - { device-name: iPhone 12 mini, appium-port: 4729, wda-port: 8107 }
          - { device-name: iPhone 11 Pro, appium-port: 4730, wda-port: 8108 }
          - { device-name: iPhone 8, appium-port: 4731, wda-port: 8109 }
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check Xcode version
        run: |
          xcodebuild -version
          xcrun simctl list devices

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "${{ matrix.config.device-name }}"
          xcrun simctl list | grep Booted

      - name: Get Booted Simulator UDID
        run: |
          DEVICE_UUID=$(xcrun simctl list devices | grep -i booted | grep -i "${{ matrix.config.device-name }}" | awk -F '[()]+' '{print $2}')
          echo "DEVICE_UUID=$DEVICE_UUID" >> $GITHUB_ENV

      - name: Setup Appium
        run: |
          npm install -g appium@v2.0.1
          appium driver install xcuitest@7.11.3
          appium -v
          appium -p ${{ matrix.config.appium-port }} &>/dev/null &

      - name: Run Appium iOS tests
        run: |
          mvn clean test -PiOS -Ddevice.name="${{ matrix.config.device-name }}" -Dappium.port=${{ matrix.config.appium-port }}