name: Appium iOS

on:
  push:
    branches: [ ios ]
  pull_request:
    branches: [ ios ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup appium
        run: |
          npm install -g appium@v2.0.1
          appium driver install xcuitest
          appium -v
          appium &>/dev/null &

      - name: Run appium ios tests
        run: |
            mvn clean test -PiOS